version: '3'

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    restart: always